# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Friend.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Friend.proto',
  package='aiins',
  syntax='proto3',
  serialized_options=b'\n\027com.example.aiins.proto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0c\x46riend.proto\x12\x05\x61iins\"!\n\rSearchUserReq\x12\x10\n\x08username\x18\x01 \x01(\t\"P\n\rSearchUserRsp\x12\x12\n\nresultCode\x18\x01 \x01(\x05\x12\x10\n\x08nickname\x18\x02 \x01(\t\x12\x0b\n\x03uid\x18\x03 \x01(\x05\x12\x0c\n\x04icon\x18\x04 \x01(\x0c\":\n\x0c\x41\x64\x64\x46riendReq\x12\x0c\n\x04\x66rom\x18\x01 \x01(\x05\x12\n\n\x02to\x18\x02 \x01(\x05\x12\x10\n\x08isAccept\x18\x03 \x01(\x08\x42\x19\n\x17\x63om.example.aiins.protob\x06proto3'
)




_SEARCHUSERREQ = _descriptor.Descriptor(
  name='SearchUserReq',
  full_name='aiins.SearchUserReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='aiins.SearchUserReq.username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=56,
)


_SEARCHUSERRSP = _descriptor.Descriptor(
  name='SearchUserRsp',
  full_name='aiins.SearchUserRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='resultCode', full_name='aiins.SearchUserRsp.resultCode', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='nickname', full_name='aiins.SearchUserRsp.nickname', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='uid', full_name='aiins.SearchUserRsp.uid', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='icon', full_name='aiins.SearchUserRsp.icon', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=138,
)


_ADDFRIENDREQ = _descriptor.Descriptor(
  name='AddFriendReq',
  full_name='aiins.AddFriendReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='from', full_name='aiins.AddFriendReq.from', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='to', full_name='aiins.AddFriendReq.to', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='isAccept', full_name='aiins.AddFriendReq.isAccept', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=140,
  serialized_end=198,
)

DESCRIPTOR.message_types_by_name['SearchUserReq'] = _SEARCHUSERREQ
DESCRIPTOR.message_types_by_name['SearchUserRsp'] = _SEARCHUSERRSP
DESCRIPTOR.message_types_by_name['AddFriendReq'] = _ADDFRIENDREQ
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SearchUserReq = _reflection.GeneratedProtocolMessageType('SearchUserReq', (_message.Message,), {
  'DESCRIPTOR' : _SEARCHUSERREQ,
  '__module__' : 'Friend_pb2'
  # @@protoc_insertion_point(class_scope:aiins.SearchUserReq)
  })
_sym_db.RegisterMessage(SearchUserReq)

SearchUserRsp = _reflection.GeneratedProtocolMessageType('SearchUserRsp', (_message.Message,), {
  'DESCRIPTOR' : _SEARCHUSERRSP,
  '__module__' : 'Friend_pb2'
  # @@protoc_insertion_point(class_scope:aiins.SearchUserRsp)
  })
_sym_db.RegisterMessage(SearchUserRsp)

AddFriendReq = _reflection.GeneratedProtocolMessageType('AddFriendReq', (_message.Message,), {
  'DESCRIPTOR' : _ADDFRIENDREQ,
  '__module__' : 'Friend_pb2'
  # @@protoc_insertion_point(class_scope:aiins.AddFriendReq)
  })
_sym_db.RegisterMessage(AddFriendReq)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
