# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Personal.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Personal.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\n\027com.example.aiins.proto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0ePersonal.proto\"\x84\x01\n\nSettingReq\x12\x0c\n\x04type\x18\x01 \x01(\x05\x12\x1c\n\x07iconReq\x18\x02 \x01(\x0b\x32\x0b.SetIconReq\x12$\n\x0bnicknameReq\x18\x03 \x01(\x0b\x32\x0f.SetNicknameReq\x12$\n\x0bpasswordReq\x18\x04 \x01(\x0b\x32\x0f.SetPasswordReq\"\'\n\nSetIconReq\x12\x0b\n\x03uid\x18\x01 \x01(\x05\x12\x0c\n\x04icon\x18\x02 \x01(\x0c\"/\n\x0eSetNicknameReq\x12\x0b\n\x03uid\x18\x01 \x01(\x05\x12\x10\n\x08nickname\x18\x02 \x01(\t\"7\n\x0eSetPasswordReq\x12\x0b\n\x03uid\x18\x01 \x01(\x05\x12\x0b\n\x03old\x18\x02 \x01(\t\x12\x0b\n\x03new\x18\x03 \x01(\t\"-\n\nSettingRsp\x12\x12\n\nresultCode\x18\x01 \x01(\x05\x12\x0b\n\x03msg\x18\x02 \x01(\tB\x19\n\x17\x63om.example.aiins.protob\x06proto3'
)




_SETTINGREQ = _descriptor.Descriptor(
  name='SettingReq',
  full_name='SettingReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='SettingReq.type', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='iconReq', full_name='SettingReq.iconReq', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='nicknameReq', full_name='SettingReq.nicknameReq', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='passwordReq', full_name='SettingReq.passwordReq', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=151,
)


_SETICONREQ = _descriptor.Descriptor(
  name='SetIconReq',
  full_name='SetIconReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='uid', full_name='SetIconReq.uid', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='icon', full_name='SetIconReq.icon', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=153,
  serialized_end=192,
)


_SETNICKNAMEREQ = _descriptor.Descriptor(
  name='SetNicknameReq',
  full_name='SetNicknameReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='uid', full_name='SetNicknameReq.uid', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='nickname', full_name='SetNicknameReq.nickname', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=194,
  serialized_end=241,
)


_SETPASSWORDREQ = _descriptor.Descriptor(
  name='SetPasswordReq',
  full_name='SetPasswordReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='uid', full_name='SetPasswordReq.uid', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='old', full_name='SetPasswordReq.old', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='new', full_name='SetPasswordReq.new', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=243,
  serialized_end=298,
)


_SETTINGRSP = _descriptor.Descriptor(
  name='SettingRsp',
  full_name='SettingRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='resultCode', full_name='SettingRsp.resultCode', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='msg', full_name='SettingRsp.msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=300,
  serialized_end=345,
)

_SETTINGREQ.fields_by_name['iconReq'].message_type = _SETICONREQ
_SETTINGREQ.fields_by_name['nicknameReq'].message_type = _SETNICKNAMEREQ
_SETTINGREQ.fields_by_name['passwordReq'].message_type = _SETPASSWORDREQ
DESCRIPTOR.message_types_by_name['SettingReq'] = _SETTINGREQ
DESCRIPTOR.message_types_by_name['SetIconReq'] = _SETICONREQ
DESCRIPTOR.message_types_by_name['SetNicknameReq'] = _SETNICKNAMEREQ
DESCRIPTOR.message_types_by_name['SetPasswordReq'] = _SETPASSWORDREQ
DESCRIPTOR.message_types_by_name['SettingRsp'] = _SETTINGRSP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SettingReq = _reflection.GeneratedProtocolMessageType('SettingReq', (_message.Message,), {
  'DESCRIPTOR' : _SETTINGREQ,
  '__module__' : 'Personal_pb2'
  # @@protoc_insertion_point(class_scope:SettingReq)
  })
_sym_db.RegisterMessage(SettingReq)

SetIconReq = _reflection.GeneratedProtocolMessageType('SetIconReq', (_message.Message,), {
  'DESCRIPTOR' : _SETICONREQ,
  '__module__' : 'Personal_pb2'
  # @@protoc_insertion_point(class_scope:SetIconReq)
  })
_sym_db.RegisterMessage(SetIconReq)

SetNicknameReq = _reflection.GeneratedProtocolMessageType('SetNicknameReq', (_message.Message,), {
  'DESCRIPTOR' : _SETNICKNAMEREQ,
  '__module__' : 'Personal_pb2'
  # @@protoc_insertion_point(class_scope:SetNicknameReq)
  })
_sym_db.RegisterMessage(SetNicknameReq)

SetPasswordReq = _reflection.GeneratedProtocolMessageType('SetPasswordReq', (_message.Message,), {
  'DESCRIPTOR' : _SETPASSWORDREQ,
  '__module__' : 'Personal_pb2'
  # @@protoc_insertion_point(class_scope:SetPasswordReq)
  })
_sym_db.RegisterMessage(SetPasswordReq)

SettingRsp = _reflection.GeneratedProtocolMessageType('SettingRsp', (_message.Message,), {
  'DESCRIPTOR' : _SETTINGRSP,
  '__module__' : 'Personal_pb2'
  # @@protoc_insertion_point(class_scope:SettingRsp)
  })
_sym_db.RegisterMessage(SettingRsp)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
